# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170206_1039'),
        ('main', '0004_post_post_img'),
    ]

    operations = [
    ]
