# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170206_0625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'My images'},
        ),
    ]
