# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170205_1640'),
        ('main', '0004_post_post_img'),
    ]

    operations = [
    ]
