# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 21:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_catsubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catsubscriber',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='catsubscriber',
            name='user_id',
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CatSubscriber',
        ),
    ]
