# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170206_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply_comment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.comment'),
        ),
    ]
